//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szwlFormsApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("szwlFormsApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.5.2&quot; /&gt;
        ///  &lt;/startup&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;systemPath&quot; value=&quot;C:\Users\Public\Documents\szwlFormsApplication&quot; /&gt;
        ///    &lt;add key=&quot;LogDirectory&quot; value=&quot;C:\Users\Public\Documents\szwlFormsApplication&quot; /&gt;
        ///    &lt;add key=&quot;tem_file&quot; value=&quot;C:\Users\Public\Documents\szwlFormsApplication\tem&quot; /&gt;
        ///    &lt;add key=&quot;isRFID&quot; value=&quot;0&quot; /&gt;
        ///    &lt;add key=&quot;packagepath&quot; value=&quot;C:\Use [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Chinese&gt;
        ///	&lt;app_name&gt;深圳物联呼叫系统&lt;/app_name&gt;
        ///	&lt;no_quest&gt;&lt;/no_quest&gt;
        ///	&lt;have_quest&gt;{0}号桌{1}类型：{2}&lt;/have_quest&gt;
        ///	&lt;no_device&gt; 获取设备端口失败，请确认插入对应设备？&lt;/no_device&gt;
        ///	&lt;prompt&gt;提示&lt;/prompt&gt;
        ///	&lt;empty_warn&gt;信息禁止为空！&lt;/empty_warn&gt;
        ///	&lt;login_prompt&gt;登录提示&lt;/login_prompt&gt;
        ///	&lt;welcome&gt;欢迎登录本系统！&lt;/welcome&gt;
        ///	&lt;login_error&gt;用户名或密码不正确！&lt;/login_error&gt;
        ///	&lt;number&gt;号码&lt;/number&gt;
        ///	&lt;nothing&gt;无&lt;/nothing&gt;
        ///	&lt;name&gt;姓名:&lt;/name&gt;
        ///	&lt;finish&gt;完成&lt;/finish&gt;
        ///	&lt;overtime&gt;超时&lt;/overtime&gt;
        ///	&lt;waiting&gt;等待&lt;/waiting&gt;
        ///	&lt;satisfy&gt;满意&lt;/sat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;English&gt;
        ///	&lt;app_name&gt;SZWL caller system&lt;/app_name&gt;
        ///	&lt;no_quest&gt;&lt;/no_quest&gt;
        ///	&lt;have_quest&gt;Number: {0}{1}Type：{2}&lt;/have_quest&gt;
        ///	&lt;no_device&gt; Failed to get device port. Make sure to insert device?&lt;/no_device&gt;
        ///	&lt;prompt&gt;Prompt&lt;/prompt&gt;
        ///	&lt;empty_warn&gt;Can&apos;t be null！&lt;/empty_warn&gt;
        ///	&lt;login_prompt&gt;Prompt&lt;/login_prompt&gt;
        ///	&lt;welcome&gt;Welcome！&lt;/welcome&gt;
        ///	&lt;login_error&gt;username or password is wrong！&lt;/login_error&gt;
        ///	&lt;number&gt;Number &lt;/number&gt;
        ///	&lt;nothing&gt;NO&lt;/nothing&gt;
        ///	&lt;name&gt;name:&lt;/na [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Record {
            get {
                object obj = ResourceManager.GetObject("Record", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Record_en {
            get {
                object obj = ResourceManager.GetObject("Record_en", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Summary {
            get {
                object obj = ResourceManager.GetObject("Summary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Summary_en {
            get {
                object obj = ResourceManager.GetObject("Summary_en", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
